### ISSUE TITLE
toAtomicString throws error when passing small number

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-protocols#933]
`toAtomicString('0.00009193', 6)` will give this error:

```
index.ts:269 Uncaught Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at Logger.makeError (index.ts:269:1)
    at Logger.throwError (index.ts:281:1)
    at throwFault (fixednumber.ts:19:1)
    at parseFixed (fixednumber.ts:104:1)
    at Module.parseUnits (index.ts:80:1)
    at toAtomicString (index.ts:597:1)
```

**Comment by piersss** [comment]
This is intentional, closing ticket.
